apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: distributed-fibonacci
  namespace: argocd
spec:
  description: Distributed Fibonacci workloads
  sourceRepos:
    - https://github.com/binary-h0/distributed-fibonacci-gitops.git
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fibo-applications
  namespace: argocd
spec:
  project: distributed-fibonacci
  source:
    repoURL: https://github.com/binary-h0/distributed-fibonacci-gitops.git
    targetRevision: HEAD
    path: apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true